### ISSUE TITLE
Where can I get the Label mapping?

### ISSUE THREAD

**Issue by zqxiaojin** [divamgupta/image-segmentation-keras#75] opened 2019-07-01 10:43 UTC
I will get a image which fill with different color after run predict.

Where can I get the color's meaning ? 

For example the No.0 class  means what, the red color means what label?

**Comment by divamgupta** [comment] 2019-07-01 14:54
Duplicate of : https://github.com/divamgupta/image-segmentation-keras/issues/67

**Closed by divamgupta** 2019-07-01 14:54 UTC
